apiVersion: v1
kind: Service
metadata:
  labels:
    app: t3-sample-app
  name: t3-sample-app
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: t3-sample-app
  type: LoadBalancer
