apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: t3-sample-app
  namespace: argocd
spec:
  destination:
    namespace: tenant-3
    server: https://kubernetes.default.svc
  project: tenant-3
  source:
    path: manifests/tenant-3/sample-app/overlays/dev
    repoURL: https://github.com/multi-tenant-example-org/tenant-3.git
    targetRevision: HEAD
