apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-app
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: sample-app
  source:
    path: manifest/tennant-3/sample-app/overlays/dev
    repoURL: https://github.com/multi-tenant-example-org/tenant-3.git
    targetRevision: HEAD
